
server:
   port: 8081

spring:
  application:
      name: estore-cloud-gateway
  profiles:
      active : development
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"


  
