   
server:
  port : 8761

spring:
   application:
     name : estore-service-registry
   cloud:
      config:
        uri : http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
