   
server:
  port : 9761

spring:
   application:
     name : estore-service-registry
   
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9761/eureka/
