server:
  port : 8081
  servlet:
    context-path : /order
spring:
  application:
    name: estore-order-mgmt-service
  profiles:
    active: development
  datasource:
    url : jdbc:mysql://localhost:3306/book_order
    username : root
    password : root
  
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
