
server:
   port: 8081
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    
spring:
  application:
    name: estore-order-mgmt-service
  profiles:
    active: development
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/book_order
    username : root
    password : root
